version: '3.1'

services:
  dynamo:
    image: amazon/dynamodb-local
    container_name: trip-app-dynamo
    ports:
      - "8000:8000"
    volumes:
      - ./dynamo:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]